export const statesCities = [
  {
    name: "Maharashtra",
    cities: [
      "Mumbai",
      "Pune",
      "Nagpur",
      "Nashik",
      "Thane",
      "Aurangabad",
      "Solapur",
      "Nasik",
      "Amravati",
      "Kolhapur",
    ],
  },
  {
    name: "Tamil Nadu",
    cities: [
      "Chennai",
      "Coimbatore",
      "Madurai",
      "Tiruchirappalli",
      "Salem",
      "Erode",
      "Tirunelveli",
      "Vellore",
      "Thoothukudi",
      "Dindigul",
    ],
  },
  {
    name: "Karnataka",
    cities: [
      "Bengaluru",
      "Mysuru",
      "Mangaluru",
      "Hubli",
      "Belagavi",
      "Davangere",
      "Ballari",
      "Bidar",
      "Shimoga",
      "Raichur",
    ],
  },
  {
    name: "Uttar Pradesh",
    cities: [
      "Lucknow",
      "Kanpur",
      "Ghaziabad",
      "Agra",
      "Varanasi",
      "Meerut",
      "Prayagraj",
      "Bareilly",
      "Aligarh",
      "Moradabad",
    ],
  },
  {
    name: "West Bengal",
    cities: [
      "Kolkata",
      "Howrah",
      "Durgapur",
      "Siliguri",
      "Asansol",
      "Bardhaman",
      "Kharagpur",
      "Malda",
      "Haldia",
      "Baharampur",
    ],
  },
  {
    name: "Gujarat",
    cities: [
      "Ahmedabad",
      "Surat",
      "Vadodara",
      "Rajkot",
      "Bhavnagar",
      "Jamnagar",
      "Gandhinagar",
      "Navsari",
      "Anand",
      "Bharuch",
    ],
  },
  {
    name: "Rajasthan",
    cities: [
      "Jaipur",
      "Jodhpur",
      "Udaipur",
      "Bikaner",
      "Kota",
      "Ajmer",
      "Alwar",
      "Bhilwara",
      "Sikar",
      "Tonk",
    ],
  },
  {
    name: "Andhra Pradesh",
    cities: [
      "Visakhapatnam",
      "Vijayawada",
      "Guntur",
      "Nellore",
      "Kurnool",
      "Tirupati",
      "Rajahmundry",
      "Kadapa",
      "Anantapur",
      "Eluru",
    ],
  },
  {
    name: "Punjab",
    cities: [
      "Ludhiana",
      "Amritsar",
      "Jalandhar",
      "Patiala",
      "Bathinda",
      "Mohali",
      "Hoshiarpur",
      "Pathankot",
      "Kapurthala",
      "Firozpur",
    ],
  },
  {
    name: "Telangana",
    cities: [
      "Hyderabad",
      "Warangal",
      "Nizamabad",
      "Khammam",
      "Karimnagar",
      "Ramagundam",
      "Mahbubnagar",
      "Adilabad",
      "Suryapet",
      "Nalgonda",
    ],
  },
];
